---
layout: inner
categories: eventos	
permalink: /rsjug-devjava-girls-na-thoughtworks/
tags:
- evento
- devsjavagirls
- apis
- microservicos
- monolitico
- boaspraticas
- versionamento
excerpt: Duas das maiores comunidades de desenvolvedores Java do Rio Grande do Sul promovem um evento na ThoughtWorks com palestras sobre carreira e boas práticas de APIs.  
comments: true
author: jsouzajava
---
= *Encontro DevJava Girls & RSJUG de Setembro*
:toc:
:icons: font
:hardbreaks:
:revdate: 2019-09-28 14:00:00 GMT-0300
:link-inscricoes: http://sucesurs.org.br/evento/dev-java-girls-rsjug-evento-thoughtworks/

Duas das maiores comunidades de desenvolvedores Java do Rio Grande do Sul promovem um evento com palestras sobre carreira e Java. Unindo todos para uma troca de conhecimentos, compartilhamento de ideias e experiências. Participe e aumente sua rede de contatos junto com o grupo Devs JavaGirls que estão inseridas num contexto nacional e o RSJUG que atua fortemente no contexto regional.

Promover um evento com tecnologias de Java, APIs e melhores práticas, com palestras falando sobre o contexto do spring e suas peculiaridades. Como as empresas estão trabalhando neste contexto novo, e exemplos práticos de como é usado no mercado de trabalho.
 
O evento ocorrerá no dia *28 de setembro* das *14:00 às 18:00*.

== Palestrantes

 
=== Fabiane Marques

Desenvolvedora de software há mais de 10 anos, formada em Sistemas de Informação. Entusiasta de java, apaixonada por livros e praias.


=== Lilian Cavalet

Encontra-se em uma carreira na área de desenvolvimento de softwares. Ela possui 7 anos de experiência no meio acadêmico e está há dois anos no meio corporativo. Atualmente cursa Informática Biomédica e tem trabalhado com desenvolvimento em Java. Entre seus maiores interesses, estão: aprender, experimentar culinárias distintas e board games.


=== Alessandro Silva da Silva

Profissional de TI com início das suas atividades no ano de 2009, atuando com suporte, implantação de sistemas, ingressou na área de desenvolvimento em 2014, atualmente trabalha em projetos com arquitetura de microsserviços. Gosta de aprender e ensinar, apaixonado por música, futebol, churrasco e chimarrão.

=== Kaio Ferreira

Analista de Sistemas/Desenvolvedor Java, trabalhando atualmente com arquitetura de microsserviços, que adora aprender e compartilhar assuntos referentes ao ecossistema Java. Minha missão é ajudar quem queira aprender sobre programação, evoluindo em sua jornada profissional e pessoal.


== Programação

icon:check-square-o[] 14:00 Recepção / Abertura (Devs JavaGirls + RSJUG)
icon:check-square-o[] 14:15 Palestra *Yes, she codes* Fabiane Marques
icon:check-square-o[] 15:00 Palestra *Annotations: do Java 5 ao SpringBoot* Lilian Cavalet
icon:check-square-o[] 15:45 Coffee
icon:check-square-o[] 16:00 Palestra *Introdução ao REST e ao mapeamento de sua API RESTful* Alessandro Silva da Silva
icon:check-square-o[] 16:45 Palestra *Boas práticas no Versionamento APIs* Kaio Ferreira
icon:check-square-o[] 17:30 Encerramento
 
== Local

Av. Ipiranga, 6681, TECNOPUC, ThoughtWorks Brazil - Prédio, 99A - 14 andar - sala 1402

== Inscrições

Inscrições gratuitas em {link-inscricoes}.
	


 


