---
layout: inner
categories: eventos	
permalink: /rsjug-devjava-girls/
tags:
- evento
- software design
- Devjava Girls
- Venkat
- carreira
excerpt: Brasil JugTour trará para Porto Alegre um dos maiores palestrantes do mundo o Dr. Venkat Subramaniam seguido de um dos evangelistas mais influentes do mundo Java, Bruno Souza o JavaMan!
comments: true
author: rmpestano
---
= *Encontro DevJava Girls & RSJug*
:toc:
:icons: font
:hardbreaks:
:revdate: 2019-03-27 10:00:00 GMT-0300
:link-inscricoes: http://www.sucesurs.org.br/evento/encontro-devjava-girls-rsjug/

Duas das maiores comunidades de desenvolvedores Java do Rio Grande do Sul promovem um evento com palestras sobre `DevOps` e  `micro serviços`. Unindo todos para uma troca de conhecimentos, compartilhamento de ideias e experiências.

Participe e aumente sua rede de contatos junto com o grupo `Devs JavaGirls` que estão inseridas num contexto nacional e o `RSJug` que atua fortemente no contexto regional.
 
 
== Palestrantes

 
=== Thaiane Braga

Rubista, feminista e ativista. Engenheira de Software pela Universidade de Brasília e consultora desenvolvedora na Thoughtworks – Porto Alegre. Coorganizadora do Afropython.


 
=== Ruan Victor

Baiano, viciado em Bojack Horseman. Consultor e pedreiro de software na Thoughtworks. De vez em quando escreve para a Training Center.

=== Savanna Denega

Savanna já esteve atuando nas áreas de Robótica e Pesquisa/Iniciação Científica. Hoje trabalha como desenvolvedora back-end Java na IBM, é estudante de Ciência da Computação e adora participar e compartilhar conhecimento nas comunidades de tecnologia, assim participando da comunidade Devs Java Girls de POA e apoiando outros projetos, como o Django Girls.


=== Sebastian Webber

Sou um profissional da área de TI com mais de 10 anos de experiência, especialmente em desenvolvimento de software e administração de banco de dados. Trabalho com PostgreSQL desde a versão 8.0 e hoje trabalho como SRE em alguns projetos. Eu amo aprender novas tecnologias mas hoje me emociono criando ferramentas de automação usando a linguagem de programação Go e compartilhar minhas experiências nos eventos de TI.

=== Heleno da Silva Alves

Engenheiro de Software – +14 Anos de Experiência.



== Programação

icon:check-square-o[] 09:00 Recepção / Abertura (Devs JavaGirls + RSJUG)
icon:check-square-o[] 09:15 Palestra Desafios de segurança em arquitetura de microsserviços com Thaiane Braga e Ruan Victor
icon:check-square-o[] 10:00 Palestra DevOps na prática com Savannah
icon:check-square-o[] 10:45 Coffee
icon:check-square-o[] 11:00 Palestra Coding Challenges em Java – Além dos Frameworks com Heleno da Silva Alves
icon:check-square-o[] 11:45 Palestra Domando o Java sob containers com Sebastian Webber
icon:check-square-o[] 12:30 Encerramento
 
== Local

TECNOPUC, Av. Ipiranga, 6681, Predio 99A Sala 204

== Inscrições

Inscrições gratuitas em {link-inscricoes}.
	


 


